### ISSUE TITLE
[Bug] hot module reloading not working

### ISSUE THREAD

**Issue by kaseymccurdy** [creativetimofficial/ct-nuxt-argon-dashboard-pro#1]
### Version
 1.0.0
### Reproduction link
https://www.dropbox.com/s/kjutmz9dtexyczg/workhound-vue-dashboard.zip?dl=0
### Operating System
oaxosx 10.14.4
### Device
laptop
### Browser & Version
chrome & firefox
### Steps to reproduce
1. download the referenced zip file and unzip it
2. `npm i` to install the modules
3. `npm run dev` to start the server
4. navigate to http://localhost:3000/skeletons/activity
5. make a change to `.activity-user-comment-header` or add any other styles 
6. notice that you see a message in the console of the browser saying: `[HMR] Nothing hot updated.`
### What is expected?
I would expect HMR to pick up the file changes and load the css without me having to refresh the page. after a few edits, HMR stops picking up the changes.
### What is actually happening?
i have to do a refresh each time to see my new changes.

---
### Additional comments
- note - the first couple of changes may take effect, but subsequent changes will not.

**Comment by kaseymccurdy** [comment]
Curious if anyone has had a chance to read this up yet? Can i provide more info at all?

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
