### ISSUE TITLE
[Bug] Build error upon first build

### ISSUE THREAD

**Issue by vanozi** [creativetimofficial/ct-nuxt-argon-dashboard-pro#12]
### Version
v1.1.1
### Reproduction link
http://N/A.com
### Operating System
Manjaro Linux
### Device
Lapotop
### Browser & Version
N/A
### Steps to reproduce
Buy nuxt argon dashboard pro
download the vue project
yarn or npm install dependencies
npm or yarn dev
### What is expected?
A build without failures
### What is actually happening?
 ERROR  Failed to compile with 1 errors                                                                                                                             friendly-errors 21:06:16

This dependency was not found:                                                                                                                                      friendly-errors 21:06:16
                                                                                                                                                                    friendly-errors 21:06:16
* @/components/Feed/Comment in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/pages/dashboard/ActivityFeed.vue?vue&type=script&lang=js&
                                                                                                                                                                    friendly-errors 21:06:16
To install it, you can run: npm install --save @/components/Feed/Comment                                                                                            friendly-errors 21:06:16

---

**Comment by tobkle** [comment]
same for me

**Comment by mytwink** [comment]
just change components/pages/dashboard/ActivityFeed.vue. Replace '@/components/Feed/Comment' to '@/components/feed/Comment'.

**Comment by cristijora** [comment]
This issue was fixed in version 1.2.0 along with other fixes & improvements.
For more details check the detailed [changelog here](https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/changelog.html)
