### ISSUE TITLE
[Bug] Form Element BaseInput component error

### ISSUE THREAD

**Issue by arlejeun** [creativetimofficial/ct-nuxt-argon-dashboard-pro#13]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/forms/components
### Operating System
Mac OS
### Device
Mac Book Pro
### Browser & Version
Chrome latest
### Steps to reproduce
Base input does not accept any input. When you try to enter a text, nothing happens
### What is expected?
Write the text in the input field
### What is actually happening?
Nothing

---

**Comment by shhinny** [comment]
I was getting the same issue, and it only occurs when I was pulling data from the vuex-store.

After reading vee-validate, the solution was pretty simple, I just wrapped my form inside the validation-observer tag

`<validation-observer v-slot="{ invalid }">`
 `   <form  class="needs-validation"  @submit.prevent="firstFormSubmit"> `
 `          // inputs here` 
 `   </form>` 
  `</validation-observer>`

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
