### ISSUE TITLE
[Bug] Button and badge components don't work with "nuxt-link" tag

### ISSUE THREAD

**Issue by alexcbz** [creativetimofficial/ct-nuxt-argon-dashboard-pro#14]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/components/badges.html
### Operating System
MacOS 10.15.3
### Device
Macbook
### Browser & Version
Chrome 80
### Steps to reproduce
1. Load a `base-button` or `badge` into the page
2. Pass `tag` prop with "nuxt-link" value
3. Add `to` prop with a valid path or URL

Example:
`<badge rounded tag="nuxt-link" to="/about" type="default">About us</badge>`

### What is expected?
To show the button or the badge as a "Nuxt link". It works with `a` tag, but this involves full page refresh in Nuxt, which is not desired.
### What is actually happening?
You will get an error: "[Vue warn]: Missing required prop: "to""

---

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
