### ISSUE TITLE
[Bug] Alert notification flashes on hover

### ISSUE THREAD

**Issue by ramigs** [creativetimofficial/ct-nuxt-argon-dashboard-pro#16]
### Version
1.0.0
### Reproduction link
https://raw.githubusercontent.com/ramigs/media-hosting/master/nuxt-argon-alert-issue.gif
### Operating System
macOS
### Device
Macbook Pro
### Browser & Version
Chrome Version 81.0.4044.122
### Steps to reproduce
1. Fire alert notification:
<notifications></notifications>

      this.$notify({
        type: 'danger',
        message:
          'File extension not supported. Please upload a jpgeg/png image.'
      })

2. Hover mouse over notification alert
### What is expected?
Notification alert to remain the same on mouse hover.
### What is actually happening?
When hovering the mouse over the alert it flashes very quickly (see attached gif).

---
### Solution
Found a workaround by commenting lines 15-17 in assets/sass/core/alerts/_alert-notify.scss:

 &:hover {
        z-index: 1081 !important;
    }

This is fixing my issue, just wanted to share the solution and ask if this has any impact on something else it shouldn't.
### Additional comments
Thanks for your product!
We've been using it and its helping us deliver faster and better.

Just something I think could be improved is if the project already came with eslint and prettier.
I've tried to add them, but at this point it's just not manageable to do it in a codebase with this dimension.

Also would like to see more advanced examples on how to reuse pre-made components and elements.

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
