### ISSUE TITLE
[Bug]Cannot change vee-validate translation on my form

### ISSUE THREAD

**Issue by GELELOIC** [creativetimofficial/ct-nuxt-argon-dashboard-pro#17]
### Version
1.2.1
### Reproduction link
https://codesandbox.io/s/veevalidate-30-basic-i18n-forked-4lq69?fontsize=14&hidenavigation=1&theme=dark&file=/src/vee-validate.js
### Operating System
Linux
### Device
MSI
### Browser & Version
Chrome 84.0.4147.135
### Steps to reproduce
1. Focus input
2. Blur input
### What is expected?
The error label is in french
### What is actually happening?
The error label not in french

---
### Additional comments
Thanks for your product!

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
