### ISSUE TITLE
[Bug] bootstrap tabs not working

### ISSUE THREAD

**Issue by andrewbeyer** [creativetimofficial/ct-nuxt-argon-dashboard-pro#18]
### Version
1.2.0
### Reproduction link
http://none.com
### Operating System
windows 10
### Device
laptop
### Browser & Version
firefox 80.0.1
### Steps to reproduce
step 1: copy any code for tabs from here: https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/components/tabs.html
step 2: paste them in a new or an existing page of your nuxt argon pro template
step 3: watch how it doesn't work
### What is expected?
it is expected to show the tabs
### What is actually happening?
it doesn't show the tabs and show the text instead

---
### Solution
i have none

**Comment by barmarko27** [comment]
Make sure to import and register components:

`import Tabs from '@/components/argon-core/Tabs/Tabs'
import TabPane from '@/components/argon-core/Tabs/Tab'`

`export default {
  components: {
    Tabs,
    TabPane,`

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
