### ISSUE TITLE
[Bug] Clicking links in modal results to a non-scrollable page

### ISSUE THREAD

**Issue by emanlodovice** [creativetimofficial/ct-nuxt-argon-dashboard-pro#19]
### Version
1.2.0
### Reproduction link
https://example.com
### Operating System
Ubuntu 18.04
### Device
Desktop Computer
### Browser & Version
Google Chrome 87.0.4280.66
### Steps to reproduce
1. Create a modal
2. add a `<n-link>` component in this modal to a different page with a long content
3. click that link
### What is expected?
The scrollbar should be visible.
### What is actually happening?
The page is not scollable.

---

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
