### ISSUE TITLE
[Bug] Search field in Paginated tables doesn't work

### ISSUE THREAD

**Issue by MielPoule** [creativetimofficial/ct-nuxt-argon-dashboard-pro#21]
### Version
1.3.0
### Reproduction link
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/tables/paginated
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Chrome 92.0.4515.13
### Steps to reproduce
1 - Open the link to the Paginated tables demo page : https://demos.creative-tim.com/nuxt-argon-dashboard-pro/tables/paginated
2 - Search for anything in the search field
3 - Results data in table is invisible :O
### What is expected?
Show the results data
### What is actually happening?
The data is not visible

---

**Comment by MielPoule** [comment]
To fix the search field : 
In clientPaginationMixin.js 
  
`searchQuery(value) {
     let result = this.tableData
     if (value !== '') {
         result = this.fuseSearch.search(value)
         result = result.map((x) => x.item)
     }
     this.searchedData = result
 }`

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
