### ISSUE TITLE
[bug] type="expand" on element-ui tables not working

### ISSUE THREAD

**Issue by uxdevopstevan** [creativetimofficial/ct-nuxt-argon-dashboard-pro#24]
It seems that when adding type="expand" to table columns like so - 
`<el-table-column type="expand">`
The column does not seem to be showing the expand icon due to the column not setting a column width and defaulting to 48px wide.
However i can see that if i manually set a width on the column the icon appears and i can click it to expand the row. 
Is there an issue with the element-ui package 2.15.6?
I am using Argon v1.4.

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
