### ISSUE TITLE
i run 'yarn dev'

### ISSUE THREAD

**Issue by zgame555** [creativetimofficial/ct-nuxt-argon-dashboard-pro#25]
Error:    
Vue packages version mismatch:      
 - vue@2.6.14             
 -  vue-server-renderer@2.7.0  
 - This may cause things to work incorrectly. Make sure to use the same version for both.

**Comment by ZanePilskalne** [comment]
this is still relevant.

**Comment by ZanePilskalne** [comment]
Update vue version to match vue-server-renderer and then -> 
To get rid of the annoying warnings and solve them run in your command line first npm install -g sass-migrator and after that run sass-migrator division **/*.scss

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
