### ISSUE TITLE
nuxt 3

### ISSUE THREAD

**Issue by PouryaNoufallah96** [creativetimofficial/ct-nuxt-argon-dashboard-pro#26]
i purchased new version but it's v1.4.0 instead of v2 . what should I do?

**Comment by dragosct** [comment]
@PouryaNoufallah96 Hi! Thank for using our products. No worries, the product is updating in progress the new  archive will be uploaded asap.

**Comment by PouryaNoufallah96** [comment]
ok thanks. and one more question ,  I bought the vue bundle package last year. and I bought this new version of nuxt argon today because of nuxt 3 and I paid but in my dashboard said it is a gift . i don't know what does it mean 
![image](https://user-images.githubusercontent.com/49477528/206419831-2f6df5f8-d09f-47dd-839b-276e8fe53119.png)

**Comment by PouryaNoufallah96** [comment]
tnx for your update and i also download the new version but I got this error:
 Cannot start nuxt:  Cannot find package 'vite' imported from \argon\nuxt argon dashboard pro\nuxt-argon-dashboard-2-pro\node_modules\@vitejs\plugin-vue\dist\index.mjs

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad

**Comment by sajadevo** [comment]
@PouryaNoufallah96,

Could you please tell me that what you've did the steps that you've did after downloading the product?

Regards,
Sajad

**Comment by PouryaNoufallah96** [comment]
i ran the "npm install" command and then "npm run dev" 
i had these warnings and errors below on terminal :
![image](https://user-images.githubusercontent.com/49477528/206688406-f036c1fa-fd3d-4439-8006-7d4ee7fe8a6e.png)
![image](https://user-images.githubusercontent.com/49477528/206688438-9337fa6e-2daa-408a-854c-6963ee732eef.png)
![image](https://user-images.githubusercontent.com/49477528/206688488-777f0274-93b5-4168-bc60-301427fb44a2.png)

**Comment by sajadevo** [comment]
Hey @PouryaNoufallah96,

It's fine, it's an issue with the sass you can use the `localhost:3000` to see the live demo.

Cheers,
Sajad

**Comment by PouryaNoufallah96** [comment]
ok thank you for your support
