### ISSUE TITLE
[Feature Request] Use <el-dropdown-item>

### ISSUE THREAD

**Issue by Youhan** [creativetimofficial/ct-nuxt-argon-dashboard-pro#3]
### What is your enhancement?
Hi, 
Thanks for the product. 

I noticed you are using this markup for Element dropdowns on Tables.
```
<el-dropdown-menu class="dropdown-menu dropdown-menu-arrow show" slot="dropdown">
    <a class="dropdown-item" href="#">Action</a>
</el-dropdown-menu>
```
I assume the correct way is 
```
<el-dropdown-menu class="dropdown-menu dropdown-menu-arrow show" slot="dropdown">
    <el-dropdown-item @click.native="editRow(row.id)">Action</el-dropdown-item>
</el-dropdown-menu>
```

Thanks

**Comment by cristijora** [comment]
This can be done although, it will contain the element-ui styles. Depends on your preferences in the end but not a must to switch to `el-dropdown-item` here

**Comment by Youhan** [comment]
Thanks for your response. 
I just found out if the dropdown button action is `delete row`, without using  `<el-dropdown-item>`, after click the dropdown will remain open! which is not a good UX. 

So for row delete action, I had to use this
```
<el-dropdown-menu class="dropdown-menu dropdown-menu-arrow show" slot="dropdown">
    <el-dropdown-item @click.native="deleteRow(row.id)">Action</el-dropdown-item>
</el-dropdown-menu>
```
