### ISSUE TITLE
[Feature Request] Add Validation example for <el-select />

### ISSUE THREAD

**Issue by Youhan** [creativetimofficial/ct-nuxt-argon-dashboard-pro#4]
### What is your enhancement?
I could not found an example on how to validate on `<el-select>`. 
Could you please provide an example on your demo or here?

**Comment by maziarz** [comment]
Also need this feature.

**Comment by cristijora** [comment]
Updated to version 1.2.0 which includes an update of vee-validate (validation library).
You can find an example of custom component validations in the [changelog here](https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/changelog.html)
