### ISSUE TITLE
[Bug] sidebar error

### ISSUE THREAD

**Issue by kim-yeonjoong** [creativetimofficial/ct-nuxt-argon-dashboard-pro#6]
### Version
1.1.0
### Reproduction link
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/dashboard
### Operating System
windows
### Device
computer
### Browser & Version
chrome 77
### Steps to reproduce
run dev tool and toggle device toolbar (to mobile) and close sidebar(hide) and re change to computer view
### What is expected?
i don' know
### What is actually happening?
sidebar change to minimize mode (i remove minimize button and fix to false) and text disappear

---
### Additional comments
it's also appear in your preview so i write minimal reproduction link to your preview

**Comment by cristijora** [comment]
To everyone encountering this issue, a fix is to add this line of code inside SidebarPlugin/index.js file
![image](https://user-images.githubusercontent.com/15955045/66810535-1de0f580-ef38-11e9-92c5-a6e81d56e079.png)

**Comment by kim-yeonjoong** [comment]
this isuue fixed in new version thanks
