### ISSUE TITLE
[Bug] Validation for aleternative inputs

### ISSUE THREAD

**Issue by DavidFricker** [creativetimofficial/ct-nuxt-argon-dashboard-pro#7]
How to use the validation styles on the `alternative` input fields? It does not work when switching from normal to `alternative` input fields - like below from the demo:
image.png

![image](https://user-images.githubusercontent.com/6656039/67603200-26bf9b80-f770-11e9-9aaa-52a5b73d1b83.png)

**Comment by cristijora** [comment]
This issue was fixed in version 1.2.0 along with other fixes & improvements.
For more details check the detailed [changelog here](https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/changelog.html)
