### ISSUE TITLE
[Bug] Toggle Navigation

### ISSUE THREAD

**Issue by frankperez87** [creativetimofficial/ct-nuxt-argon-dashboard-pro#8]
### Version
1.1.1
### Reproduction link
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/dashboard
### Operating System
MacOS Catalina
### Device
MacBook Pro
### Browser & Version
Chrome Version 78
### Steps to reproduce
1. In desktop mode, click the toggle button for the navigation on the top left of the page to the right of the Argon logo.
### What is expected?
The expected output would be for the navigation to hide. 
### What is actually happening?
In desktop mode, when you click the toggle button to hide the top navigation, you'll see that the content just slides to the left behind the navigation, but the navigation stays displayed.

---

**Comment by cristijora** [comment]
Unfortunately this is how the sidebar is design. It will minimize once you move the mouse out of the sidebar. It's done like this so the sidebar expands on mouse hover over the sidebar.
Will leave this open for now and if more people find it as an issue, we can figure something out

**Comment by kleoken** [comment]
I agree, I'd also like to see the sidebar be able to be toggled without having to move the mouse out of the sidebar (and only expland when you toggle not on mouseenter) I tried getting it to do this myself but couldn't seem to find where the sidebar gets this behavior, even after disabling all of it's event handlers

**Comment by sajadevo** [comment]
Hey there,

We just update the product to nuxt 3, you can update it to the latest version to get the final updates.

Regards,
Sajad
